version: "3"

services:
  sql:
    ports:
      - 1433:1433
    networks:
      - sqlnet
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password

networks:
  sqlnet:
